//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookiesinfo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class stuimg
    {
        
        [System.ComponentModel.DisplayName("Id")]
        public Nullable<int> id { get; set; }
        [System.ComponentModel.DisplayName("First Name")]
        public string name { get; set; }
        [System.ComponentModel.DisplayName("Student Image")]
        public string img_path { get; set; }

        [System.ComponentModel.DisplayName("Photo")]
        public HttpPostedFileBase myimg { get; set; }
    }
}
