//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalImgUpload.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class student
    {
       
        public int id { get; set; }
        [DisplayName("Name")]
        public string name { get; set; }
        public string img { get; set; }
        [DisplayName("Image Upload")]
        public HttpPostedFileBase simg { get; set; }
    }
}
