//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstApprochDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSEA
    {
        public int id { get; set; }
        public string name { get; set; }
        public int Age { get; set; }
    }
}
